include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
  errors:
    missing_return: error
    dead_code: warning

linter:
  rules:
    - use_build_context_synchronously
    - avoid_print
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - unawaited_futures
    - prefer_single_quotes
    - avoid_dynamic
    - prefer_final_locals
    - prefer_final_in_for_each
    - avoid_redundant_argument_values
    - unnecessary_const
    - unnecessary_new
    - curly_braces_in_flow_control_structures
    - prefer_collection_literals
    - prefer_if_null_operators
    - prefer_spread_collections
    - sort_child_properties_last
    - use_super_parameters
    - use_key_in_widget_constructors
    - avoid_unnecessary_containers
    - prefer_null_aware_operators
